name: Eds CI/CD Job

# --------------------------------------------------
# WHEN THE WORKFLOW RUNS
# --------------------------------------------------

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:


# --------------------------------------------------
# CONCURRENCY
# Cancel older runs for the same branch
# --------------------------------------------------

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# --------------------------------------------------
# GLOBAL VARIABLES
# --------------------------------------------------

env:
  IMAGE_NAME: library-quality-analysis


jobs:

  # ==================================================
  # TEST JOB
  # ==================================================

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4


      # Setting up Python
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: "pip"


      # Install our dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt


      # Run unittest tests
      - name: Run unittest tests
        run: |
          python -m unittest discover \
            -s testing \
            -p "*_unit_test.py" \
            -v


      # Run pytest tests
      - name: Run pytest tests
        run: |
          python -m pytest testing \
            --ignore-glob="*_unit_test.py" \
            -v


  # ==================================================
  # BUILD JOB
  # Only runs if the test job succeeds
  # ==================================================

  build:
    name: Building Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4


      # Build Docker image
      - name: Create Image
        run: |
          docker build \
            --file docker\Dockerfile \
            --tag $IMAGE_NAME:${{ github.sha }} \
            .


      # Run Docker image
      - name: Run Docker Image
        run: |
          docker run --rm \
            $IMAGE_NAME:${{ github.sha }}


      # Save Docker image as a .tar file
      - name: Save Docker Image
        run: |
          docker save \
            $IMAGE_NAME:${{ github.sha }} \
            --output $IMAGE_NAME.tar


      # Upload Docker image as a GitHub Actions artifact
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.IMAGE_NAME }}-${{ github.sha }}
          path: ${{ env.IMAGE_NAME }}.tar
          if-no-files-found: error
